[package]
name = "trfix"
version = "0.1.0"
authors = ["Yalin Gunayer <yalin.gunayer@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
chardet = "0.2.4"
walkdir = "2.2.7"
tree_magic = "0.2.1"
encoding_rs = "0.8.17"
